// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Payments.Database;

#nullable disable

namespace Payments.Database.Migrations;

[DbContext(typeof(PaymentsDbContext))]
partial class PaymentsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.28")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Payments.Domain.Payment", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
            b.Property<decimal>("Amount").HasPrecision(10, 2).HasColumnType("decimal(10,2)");
            b.Property<string>("CardLastFour").IsRequired().HasMaxLength(4).HasColumnType("nvarchar(4)");
            b.Property<DateTime?>("CapturedAtUtc").HasColumnType("datetime2");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
            b.Property<string>("FailureReason").HasMaxLength(255).HasColumnType("nvarchar(255)");
            b.Property<Guid>("ReservationId").HasColumnType("uniqueidentifier");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
            b.Property<DateTime?>("VoidedAtUtc").HasColumnType("datetime2");
            b.HasKey("Id");
            b.HasIndex("ReservationId");
            b.HasIndex("UserId", "CreatedAtUtc");
            b.ToTable("Payments", (string)null);
        });
#pragma warning restore 612, 618
    }
}
