// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using TicketPurchases.Database;

#nullable disable

namespace TicketPurchases.Database.Migrations;

[DbContext(typeof(TicketsDbContext))]
partial class TicketsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.28")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("TicketPurchases.Domain.TicketPurchase", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
            b.Property<Guid?>("PaymentId").HasColumnType("uniqueidentifier");
            b.Property<Guid?>("PurchaseId").HasColumnType("uniqueidentifier");
            b.Property<int>("PaymentMethod").HasColumnType("int");
            b.Property<DateTime>("PurchasedAtUtc").HasColumnType("datetime2");
            b.Property<decimal>("PricePaid").HasPrecision(10, 2).HasColumnType("decimal(10,2)");
            b.Property<Guid>("ReservationId").HasColumnType("uniqueidentifier");
            b.Property<Guid>("ScreeningId").HasColumnType("uniqueidentifier");
            b.Property<string>("SeatLabel").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<string>("TicketNumber").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
            b.HasKey("Id");
            b.HasIndex("PaymentId").HasFilter("[PaymentId] IS NOT NULL");
            b.HasIndex("PurchaseId");
            b.HasIndex("ReservationId").IsUnique();
            b.HasIndex("TicketNumber").IsUnique();
            b.HasIndex("UserId", "PurchasedAtUtc");
            b.ToTable("TicketPurchases", (string)null);
        });
#pragma warning restore 612, 618
    }
}
