// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Reservations.Database;

#nullable disable

namespace Reservations.Database.Migrations;

[DbContext(typeof(ReservationsDbContext))]
partial class ReservationsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.28")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Reservations.Domain.Reservation", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
            b.Property<DateTime?>("CancelledAtUtc").HasColumnType("datetime2");
            b.Property<int>("PaymentOption").HasColumnType("int");
            b.Property<DateTime>("ReservedAtUtc").HasColumnType("datetime2");
            b.Property<Guid>("ScreeningId").HasColumnType("uniqueidentifier");
            b.Property<string>("SeatLabel").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
            b.HasKey("Id");
            b.HasIndex("ScreeningId", "SeatLabel").IsUnique().HasFilter("[Status] = 'Active'");
            b.HasIndex("UserId", "ReservedAtUtc");
            b.ToTable("Reservations", (string)null);
        });
#pragma warning restore 612, 618
    }
}
