<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\GatewayApi.Domain.csproj" />
    <ProjectReference Include="..\Middlewares\GatewayApi.Middlewares.csproj" />
    <ProjectReference Include="..\Services\GatewayApi.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
  </ItemGroup>
</Project>
