import { useEffect, useState } from 'react';

const api = import.meta.env.VITE_API_GATEWAY_URL;
const empty = { movieId: '', hallId: '', startsAtUtc: '', baseTicketPrice: '' };

export default function ScreeningManagementPage({ onBack }) {
  const [movies, setMovies] = useState([]); const [halls, setHalls] = useState([]); const [screenings, setScreenings] = useState([]); const [search, setSearch] = useState(''); const [form, setForm] = useState(empty); const [message, setMessage] = useState('');
  const load = async () => { const [moviesResponse, hallsResponse, screeningsResponse] = await Promise.all([fetch(`${api}/api/movies`), fetch(`${api}/api/halls`), fetch(`${api}/api/screenings`)]); if (moviesResponse.ok) setMovies(await moviesResponse.json()); if (hallsResponse.ok) setHalls(await hallsResponse.json()); if (screeningsResponse.ok) setScreenings(await screeningsResponse.json()); };
  useEffect(() => { load(); }, []);
  const name = (items, id, field) => items.find((item) => item.id === id)?.[field] ?? 'Unknown';
  const submit = async (event) => { event.preventDefault(); const movie = movies.find((item) => item.id === form.movieId); if (!movie) return setMessage('Select a movie first.'); const start = new Date(form.startsAtUtc); const end = new Date(start.getTime() + movie.durationMinutes * 60_000); const response = await fetch(`${api}/api/screenings`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, startsAtUtc: start.toISOString(), endsAtUtc: end.toISOString(), baseTicketPrice: Number(form.baseTicketPrice) }) }); if (response.ok) { setForm(empty); setMessage('Screening added.'); load(); } else { const payload = await response.json().catch(() => ({})); setMessage(payload.message ?? 'Screening could not be created. Check that the Screenings service and Gateway are running.'); } };
  const dateTime = (value) => new Intl.DateTimeFormat('sr-RS', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
  const visible = screenings.filter((screening) => `${name(movies, screening.movieId, 'title')} ${name(halls, screening.hallId, 'name')}`.toLowerCase().includes(search.toLowerCase()));
  return <section className="management-page"><div className="management-heading"><div><p className="eyebrow">CINEMA MANAGER</p><h1>Manage screenings</h1><p>Schedule films in halls and set the base ticket price.</p></div><button className="header-link" onClick={onBack}>← Back to movies</button></div><div className="management-layout"><form className="movie-form" onSubmit={submit}><p className="eyebrow">NEW SCREENING</p><h2>Add a screening</h2><label>Movie<select value={form.movieId} onChange={(event) => setForm({ ...form, movieId: event.target.value })} required><option value="">Select a movie</option>{movies.map((movie) => <option key={movie.id} value={movie.id}>{movie.title}</option>)}</select></label><label>Hall<select value={form.hallId} onChange={(event) => setForm({ ...form, hallId: event.target.value })} required><option value="">Select a hall</option>{halls.map((hall) => <option key={hall.id} value={hall.id}>{hall.name}</option>)}</select></label><label>Starts at<input type="datetime-local" value={form.startsAtUtc} onChange={(event) => setForm({ ...form, startsAtUtc: event.target.value })} required /></label><label>Base ticket price (RSD)<input type="number" min="1" step="0.01" value={form.baseTicketPrice} onChange={(event) => setForm({ ...form, baseTicketPrice: event.target.value })} required /></label>{message && <p className="form-message">{message}</p>}<button className="submit-button">Add screening</button></form><div><label className="search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search movie or hall" /></label><div className="management-list user-list">{visible.map((screening) => <article className="manage-card" key={screening.id}><div><p className="eyebrow">{['SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED'][screening.status]}</p><h2>{name(movies, screening.movieId, 'title')}</h2><p>{name(halls, screening.hallId, 'name')} · {dateTime(screening.startsAtUtc)} · {screening.baseTicketPrice} RSD</p></div></article>)}{visible.length === 0 && <p className="state-message">No screenings found.</p>}</div></div></div></section>;
}
